language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kalpesh1999/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true kalpesh1999/docker-react npm run test